### ISSUE TITLE
basic block drops

### ISSUE THREAD

**Issue by Copetan** [collectioncard/FullyElemental#12]
I'm too big of a dummy to add drops to the basic block, maybe you should add that function @collectioncard

**Comment by collectioncard** [comment]
@Copetan What sort of drops do you want?

**Comment by Copetan** [comment]
make it drop itself

**Comment by collectioncard** [comment]
FINE

**Comment by collectioncard** [comment]
Wait... @Copetan, they do drop themselves, but they are set to act like stone. You must mine them with a pickaxe

**Comment by Copetan** [comment]
oh... i guess i didn't notice that since i can break it **instantly** with my bare hand in survival

**Comment by collectioncard** [comment]
Yeah, I need to determine the break speed still. I currently have everything set to the stone preset.
