### ISSUE TITLE
Furnace texture (new)

### ISSUE THREAD

**Issue by LeCrankyCoot** [collectioncard/FullyElemental#13]
![elemental_furnace0 2](https://user-images.githubusercontent.com/46383661/50744170-729b5700-11d5-11e9-828d-6584953ae625.png)

**Comment by collectioncard** [comment]
It looks weird, but its a good start

**Comment by LeCrankyCoot** [comment]
Unlit version
![elemental_furnace_off0 2](https://user-images.githubusercontent.com/46383661/50744247-33b9d100-11d6-11e9-9126-9978fcb6c264.png)

**Comment by LeCrankyCoot** [comment]
Keeping it simple
![elemental_furnace_sides0 2](https://user-images.githubusercontent.com/46383661/50744310-002b7680-11d7-11e9-93f9-4c81666d1c33.png)

**Comment by LeCrankyCoot** [comment]
Top and bottom
![elemental_furnace_top bottom0 2](https://user-images.githubusercontent.com/46383661/50744354-4385e500-11d7-11e9-8356-b3740d5fa710.png)

**Comment by collectioncard** [comment]
Done
