### ISSUE TITLE
biomes

### ISSUE THREAD

**Issue by Copetan** [collectioncard/FullyElemental#20]
Do you know how to make new biomes @collectioncard ? Don't have any ideas yet... but eventually I might, and we should look into it

**Comment by LeCrankyCoot** [comment]
I'd look at vanilla's BiomeProperties constructor to see how they're arranged.
I could be totally wrong but who knows

**Comment by collectioncard** [comment]
I would need to look into the class responsible for world gen... If I find the right thing, ill post it in a reply.

**Comment by collectioncard** [comment]
I have added a TestBiome class. You can look at that and pretty much copy it to add a new biome. I am going to close this issue because it shouldn't be hard from here.
