### ISSUE TITLE
remove witches, zombies, skeletons, etc

### ISSUE THREAD

**Issue by collectioncard** [collectioncard/FullyElemental#3]
(makes it more realistic, as these creatures don't exist in the real world)

**Comment by collectioncard** [comment]
Mobs will (probably) not be removed as they are hard to override, but I can stop them from spawning and should be able to disable mob spawners...

**Comment by collectioncard** [comment]
List of mobs that should probably be removed

- mooshroom
- skeleton horse
- enderman
- zombie pigman
- blaze
- chicken jockey 
- creeper
- elder guardian 
- endermite
- evoker
- ghast
- guardian
- husk
- magma cube
- shulker
- skeleton
- skeleton horseman
- slime
- spider jockey
- stray
- vex
- vindicator
- wither skeleton zombie
- zombie villager
- iron golem
- snow golem
- ender dragon
- wither


I think we can leave the ender dragon and similar mobs in if we are removing dimension access.
What do you think @Copetan

**Comment by collectioncard** [comment]
I found a way to do this. first create a new class that looks like this:

`package APackageThatYouChoose;

import net.minecraft.entity.monster.EntitySkeleton;
import net.minecraft.entity.monster.EntitySpider;
import net.minecraft.entity.monster.EntityZombie;
import net.minecraftforge.event.*;
import net.minecraftforge.event.entity.EntityJoinWorldEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

public class MobRemover{
	@SubscribeEvent
	public void onEntitySpawn(EntityJoinWorldEvent event)
	{
		if(event.getEntity() instanceof EntitySkeleton || event.getEntity() instanceof EntityZombie || event.getEntity() instanceof EntitySpider) {
	    	event.setCanceled(true);
	    }
	}
	
}
`

You should be able to add on to this as much as you want. After that, make sure to call this in the init in your main class

'MinecraftForge.EVENT_BUS.register(new MobRemover());'

**Comment by collectioncard** [comment]
@Copetan All we need to do is decide what mobs need to be removed and what can stay

**Comment by Copetan** [comment]
Okay. I think we'll be better off disabling mob spawning in the overworld for many of those mobs. I'm thinking of a method of how we could reimplement them in the game (depending on the player's progress with the mod) but I don't know yet

**Comment by collectioncard** [comment]
@Copetan ok, I still need to know what mobs to disable.

**Comment by collectioncard** [comment]
For now, I'm just gonna remove them all and we can deal with what needs to be removed and your other idea in a new issue.

- [ ] mooshroom
- [ ] skeleton horse
- [ ] enderman
- [ ] zombie pigman
- [ ] blaze
- [ ] chicken jockey
- [ ] creeper
- [ ] elder guardian
- [ ] endermite
- [ ] evoker
- [ ] ghast
- [ ] guardian
- [ ] husk
- [ ] magma cube
- [ ] shulker
- [ ] skeleton
- [ ] skeleton horseman
- [ ] slime
- [ ] spider jockey
- [ ] stray
- [ ] vex
- [ ] vindicator
- [ ] wither skeleton zombie
- [ ] zombie villager
- [ ] iron golem
- [ ] snow golem
- [ ] ender dragon
- [ ] wither

**Comment by collectioncard** [comment]
Mobs checked have been removed from game
